### ISSUE TITLE
Ensuring security 

### ISSUE THREAD

**Issue by christyleos** [TechForJustice/Carry-On#10]
Encryption/security: this is one of our unique value propositions (UVP) that is of the utmost importance to MST survivors. How can we ensure that their information is private and secure? How can we protect them from "trolls"?

**Comment by havengoer** [comment]
We can start with being HIPAA compliant. This is the standard that other applications use when handling customer information.

Based from this article, they're advocating for hosts that are already HIPAA compliant. It's something we really have to consider when we migrate to another host.

**Comment by havengoer** [comment]
Closing the issue for now!
